# 项目负责人
repository_manager = "wangxudong13804"

# 项目默认主分支，记得在仓库面板也同步
main_branch = "master"

# 这个暂时不用设置 lint那块代码的优化考虑
lint_directory = "src"

# 项目使用的规范 后面会扩展。本季度先用 afu_basic。
lint_level = "afu_basic"
